In [56]:
import os
import json
import pandas as pd

def parse_output_file(file_path):
    print(file_path)
    result = {}
    with open(file_path, 'r') as file:
        for line in file.readlines():
            print("Line: ", line)
            line = line.strip()
            tokens = line.split(":")
            result[tokens[0].strip()] = tokens[1].strip()
    if 'Query throughput' in result:
        result['query_thput'] = float(result['Query throughput'].split()[0])
    if 'False positives' in result:
        result['fp'] = float(result['False positives'].split()[0])
    if 'False positive rate' in result:
        result['fpr'] = float(result['False positive rate'].split()[0][:-1]) / 100.0 # Ignore the '%' in the result
    if 'Filter throughput' in result:
        result['filter_thput'] = float(result['Filter throughput'].split()[0])
    if 'Filtered DB throughput' in result:
        result['db_thput'] = float(result['Filtered DB throughput'].split()[0])
    if 'ReverseMap DB throughput' in result:
        result['rm_thput'] = float(result['ReverseMap DB throughput'].split()[0])
    return result

In [59]:
result_dir = "./breakEven"
experiment_runs = []
for dir in os.listdir(result_dir):
    if dir == "_sources":
        continue
    experiment_run = {}
    experiment_run['id'] = str(dir)
    with open(os.path.join(result_dir, dir, 'config.json'), 'r', encoding='utf-8') as file:
        experiment_run['config'] = json.load(file)
    with open(os.path.join(result_dir, dir, 'run.json'), 'r', encoding='utf-8') as file:
        experiment_run['context'] = json.load(file)
    output_path = os.path.join(result_dir, dir, 'output.txt')
    if os.path.exists(output_path):
        experiment_run['result'] = parse_output_file(os.path.join(result_dir, dir, 'output.txt'))
        experiment_runs.append(experiment_run)

df = pd.json_normalize(experiment_runs)
df['result.breakeven'] = df['result.db_thput']/df['result.rm_thput']
print(df.columns)
display(df)

./breakEven/3/output.txt
Line:  Adaptive (filtered, batched) throughput:

Line:  Number of inserts:     3774873

Line:  Number of updates:     3774873

Line:  Time for inserts:      8.606484

Line:  Insert throughput:     438608.030875 ops/sec

Line:  CPU time for inserts:  8.418005

Line:  Time for queries:     1.557781 s

Line:  Filter throughput:     28483536.515894 ops/sec

Line:  Filtered DB throughput:     217442.215039 ops/sec

Line:  ReverseMap DB throughput:     15850.223523 ops/sec

Line:  Query throughput:     6419387.577586 ops/sec

Line:  False positives:      17827

Line:  Num DB Queries:      17827

Line:  False positive rate:  0.178270%

./breakEven/8/output.txt
Line:  ReverseMap throughput (Only NonEmpty Queries, No Filter):

Line:  bucketSize: 0 count:0

Line:  bucketSize: 1 count:3771751

Line:  bucketSize: 2 count:1561

Line:  Num Queries:      3774873

Line:  Time for queries:     103.919409 s

Line:  Query throughput:     36325.004504 ops/sec

Line:  CPU time for queries: 37.728978 s

Line:  False positive rate:  7.549746%

./breakEven/5/output.txt
Line:  ReverseMap throughput (Only NonEmpty Queries, No Filter):

Line:  bucketSize: 0 count:0

Line:  bucketSize: 1 count:3748342

Line:  bucketSize: 2 count:13219

Line:  bucketSize: 3 count:31

Line:  Num Queries:      3774873

Line:  Time for queries:     109.858659 s

Line:  Query throughput:     34361.178576 ops/sec

Line:  CPU time for queries: 38.191810 s

Line:  False positive rate:  7.549746%

./breakEven/1/output.txt
Line:  Adaptive (filtered, batched) throughput:

Line:  Number of inserts:     3774873

Line:  Number of updates:     3774873

Line:  Time for inserts:      8.355452

Line:  Insert throughput:     451785.612556 ops/sec

Line:  CPU time for inserts:  8.176802

Line:  Time for queries:     4.668146 s

Line:  Filter throughput:     27953730.984474 ops/sec

Line:  Filtered DB throughput:     298555.822601 ops/sec

Line:  ReverseMap DB throughput:     17157.565660 ops/sec

Line:  Query throughput:     2142178.072408 ops/sec

Line:  False positives:      69937

Line:  Num DB Queries:      69937

Line:  False positive rate:  0.699370%

./breakEven/2/output.txt
Line:  Adaptive (filtered, batched) throughput:

Line:  Number of inserts:     3774873

Line:  Number of updates:     3774873

Line:  Time for inserts:      8.427222

Line:  Insert throughput:     447938.003769 ops/sec

Line:  CPU time for inserts:  8.246813

Line:  Time for queries:     2.767742 s

Line:  Filter throughput:     27999283.218350 ops/sec

Line:  Filtered DB throughput:     241517.571115 ops/sec

Line:  ReverseMap DB throughput:     15474.718564 ops/sec

Line:  Query throughput:     3613053.528833 ops/sec

Line:  False positives:      35057

Line:  Num DB Queries:      35057

Line:  False positive rate:  0.350570%

./breakEven/7/output.txt
Line:  ReverseMap throughput (Only NonEmpty Queries, No Filter):

Line:  bucketSize: 0 count:0

Line:  bucketSize: 1 count:3768299

Line:  bucketSize: 2 count:3284

Line:  bucketSize: 3 count:2

Line:  Num Queries:      3774873

Line:  Time for queries:     105.627456 s

Line:  Query throughput:     35737.611630 ops/sec

Line:  CPU time for queries: 37.645939 s

Line:  False positive rate:  7.549746%

./breakEven/6/output.txt
Line:  ReverseMap throughput (Only NonEmpty Queries, No Filter):

Line:  bucketSize: 0 count:0

Line:  bucketSize: 1 count:3761272

Line:  bucketSize: 2 count:6790

Line:  bucketSize: 3 count:7

Line:  Num Queries:      3774873

Line:  Time for queries:     100.817735 s

Line:  Query throughput:     37442.549171 ops/sec

Line:  CPU time for queries: 36.592354 s

Line:  False positive rate:  7.549746%

./breakEven/4/output.txt
Line:  Adaptive (filtered, batched) throughput:

Line:  Number of inserts:     3774873

Line:  Number of updates:     3774873

Line:  Time for inserts:      8.487494

Line:  Insert throughput:     444757.074350 ops/sec

Line:  CPU time for inserts:  8.295683

Line:  Time for queries:     1.064674 s

Line:  Filter throughput:     28793301.526333 ops/sec

Line:  Filtered DB throughput:     70206.451923 ops/sec

Line:  ReverseMap DB throughput:     14817.153256 ops/sec

Line:  Query throughput:     9392546.450838 ops/sec

Line:  False positives:      8777

Line:  Num DB Queries:      8777

Line:  False positive rate:  0.087770%

Index(['id', 'config.filter', 'config.num_queries', 'config.quotient_bits',
       'config.remainder_bits', 'config.seed', 'context.artifacts',
       'context.command', 'context.experiment.base_dir',
       'context.experiment.dependencies', 'context.experiment.mainfile',
       'context.experiment.name', 'context.experiment.repositories',
       'context.experiment.sources', 'context.heartbeat', 'context.host.cpu',
       'context.host.gpus.driver_version', 'context.host.gpus.gpus',
       'context.host.hostname', 'context.host.os',
       'context.host.python_version', 'context.meta.command',
       'context.meta.config_updates.filter',
       'context.meta.config_updates.num_queries',
       'context.meta.config_updates.quotient_bits',
       'context.meta.config_updates.remainder_bits',
       'context.meta.named_configs', 'context.meta.options.--beat-interval',
       'context.meta.options.--capture', 'context.meta.options.--comment',
       'context.meta.options.--debug', 'context.meta.options.--enforce_clean',
       'context.meta.options.--file_storage', 'context.meta.options.--force',
       'context.meta.options.--help', 'context.meta.options.--id',
       'context.meta.options.--loglevel', 'context.meta.options.--mongo_db',
       'context.meta.options.--name', 'context.meta.options.--pdb',
       'context.meta.options.--print-config',
       'context.meta.options.--priority', 'context.meta.options.--queue',
       'context.meta.options.--s3', 'context.meta.options.--sql',
       'context.meta.options.--tiny_db', 'context.meta.options.--unobserved',
       'context.meta.options.COMMAND', 'context.meta.options.UPDATE',
       'context.meta.options.help', 'context.meta.options.with',
       'context.resources', 'context.result', 'context.start_time',
       'context.status', 'context.stop_time',
       'result.Adaptive (filtered, batched) throughput',
       'result.Number of inserts', 'result.Number of updates',
       'result.Time for inserts', 'result.Insert throughput',
       'result.CPU time for inserts', 'result.Time for queries',
       'result.Filter throughput', 'result.Filtered DB throughput',
       'result.ReverseMap DB throughput', 'result.Query throughput',
       'result.False positives', 'result.Num DB Queries',
       'result.False positive rate', 'result.query_thput', 'result.fp',
       'result.fpr', 'result.filter_thput', 'result.db_thput',
       'result.rm_thput',
       'result.ReverseMap throughput (Only NonEmpty Queries, No Filter)',
       'result.bucketSize', 'result.Num Queries',
       'result.CPU time for queries', 'result.breakeven'],
      dtype='object')

,id,config.filter,config.num_queries,config.quotient_bits,config.remainder_bits,config.seed,context.artifacts,context.command,context.experiment.base_dir,context.experiment.dependencies,...,result.fp,result.fpr,result.filter_thput,result.db_thput,result.rm_thput,"result.ReverseMap throughput (Only NonEmpty Queries, No Filter)",result.bucketSize,result.Num Queries,result.CPU time for queries,result.breakeven
0,3,adaptive,10000000,22,9,799178538,[output.txt],run_experiment,/home/chesetti/Repos/skiAdaptiveQf/bench,"[numpy==1.24.4, sacred==0.8.7]",...,17827.0,0.001783,2.848354e+07,217442.215039,15850.223523,NaN,NaN,NaN,NaN,13.718558
1,8,reverse,50000000,22,10,485039567,[output.txt],run_experiment,/home/chesetti/Repos/skiAdaptiveQf/bench,"[numpy==1.24.4, sacred==0.8.7]",...,NaN,0.075497,NaN,NaN,NaN,,2 count,3774873,37.728978 s,NaN
2,5,reverse,50000000,22,7,453009688,[output.txt],run_experiment,/home/chesetti/Repos/skiAdaptiveQf/bench,"[numpy==1.24.4, sacred==0.8.7]",...,NaN,0.075497,NaN,NaN,NaN,,3 count,3774873,38.191810 s,NaN
3,1,adaptive,10000000,22,7,93775130,[output.txt],run_experiment,/home/chesetti/Repos/skiAdaptiveQf/bench,"[numpy==1.24.4, sacred==0.8.7]",...,69937.0,0.006994,2.795373e+07,298555.822601,17157.565660,NaN,NaN,NaN,NaN,17.400826
4,2,adaptive,10000000,22,8,361703794,[output.txt],run_experiment,/home/chesetti/Repos/skiAdaptiveQf/bench,"[numpy==1.24.4, sacred==0.8.7]",...,35057.0,0.003506,2.799928e+07,241517.571115,15474.718564,NaN,NaN,NaN,NaN,15.607235
5,7,reverse,50000000,22,9,874904685,[output.txt],run_experiment,/home/chesetti/Repos/skiAdaptiveQf/bench,"[numpy==1.24.4, sacred==0.8.7]",...,NaN,0.075497,NaN,NaN,NaN,,3 count,3774873,37.645939 s,NaN
6,6,reverse,50000000,22,8,819209670,[output.txt],run_experiment,/home/chesetti/Repos/skiAdaptiveQf/bench,"[numpy==1.24.4, sacred==0.8.7]",...,NaN,0.075497,NaN,NaN,NaN,,3 count,3774873,36.592354 s,NaN
7,4,adaptive,10000000,22,10,433507648,[output.txt],run_experiment,/home/chesetti/Repos/skiAdaptiveQf/bench,"[numpy==1.24.4, sacred==0.8.7]",...,8777.0,0.000878,2.879330e+07,70206.451923,14817.153256,NaN,NaN,NaN,NaN,4.738188

### Breakeven cost

In [60]:
filtered_df = df[df['config.filter']=='adaptive']
display(filtered_df.groupby(['config.quotient_bits', 'config.remainder_bits', 'config.num_queries', 'config.filter'])
        .agg({
            'result.query_thput': ['mean'],
            'result.filter_thput': ['mean'],
            'result.fpr': ['mean'],
            'result.db_thput': ['mean'],
            'result.rm_thput': ['mean'],
            'result.breakeven': ['mean']
            }))

                                                                            result.query_thput  \
                                                                                          mean
config.quotient_bits config.remainder_bits config.num_queries config.filter
22                   7                     10000000           adaptive            2.142178e+06
                     8                     10000000           adaptive            3.613054e+06
                     9                     10000000           adaptive            6.419388e+06
                     10                    10000000           adaptive            9.392546e+06

                                                                            result.filter_thput  \
                                                                                           mean
config.quotient_bits config.remainder_bits config.num_queries config.filter
22                   7                     10000000           adaptive             2.795373e+07
                     8                     10000000           adaptive             2.799928e+07
                     9                     10000000           adaptive             2.848354e+07
                     10                    10000000           adaptive             2.879330e+07

                                                                            result.fpr  \
                                                                                  mean
config.quotient_bits config.remainder_bits config.num_queries config.filter
22                   7                     10000000           adaptive        0.006994
                     8                     10000000           adaptive        0.003506
                     9                     10000000           adaptive        0.001783
                     10                    10000000           adaptive        0.000878

                                                                            result.db_thput  \
                                                                                       mean
config.quotient_bits config.remainder_bits config.num_queries config.filter
22                   7                     10000000           adaptive        298555.822601
                     8                     10000000           adaptive        241517.571115
                     9                     10000000           adaptive        217442.215039
                     10                    10000000           adaptive         70206.451923

                                                                            result.rm_thput  \
                                                                                       mean
config.quotient_bits config.remainder_bits config.num_queries config.filter
22                   7                     10000000           adaptive         17157.565660
                     8                     10000000           adaptive         15474.718564
                     9                     10000000           adaptive         15850.223523
                     10                    10000000           adaptive         14817.153256

                                                                            result.breakeven
                                                                                        mean
config.quotient_bits config.remainder_bits config.num_queries config.filter
22                   7                     10000000           adaptive             17.400826
                     8                     10000000           adaptive             15.607235
                     9                     10000000           adaptive             13.718558
                     10                    10000000           adaptive              4.738188

### DB and ReverseMap Throughput

In [ ]:
filtered_df = df[(df['config.filter']=='reverse') | (df['config.filter']=='database')]
display(filtered_df.groupby(['config.quotient_bits', 'config.remainder_bits', 'config.num_queries', 'config.filter'])
        .agg({
            'result.query_thput': ['mean'],
            'result.filter_thput': ['mean'],
            'result.fpr': ['mean'],
            'result.db_thput': ['mean'],
            'result.rm_thput': ['mean'],
            'result.breakeven': ['mean']
            }))

TypeError: Cannot perform 'ror_' with a dtyped [object] array and scalar of type [bool]